### ISSUE TITLE
Providing three_traces.pickle

### ISSUE THREAD

**Issue by RyokoNod** [berenslab/mini-atlas#3]
This is more of a request than an issue: It would be very helpful in recreating your analysis if you could somehow provide the file `three_traces.pickle`.

As it is now, we need to download the NWB files and run `preprocess-ephys-files.ipynb` from scratch in order to get it. And if we aren't very careful, we end up overwriting `m1_patchseq_ephys_features.csv` and `m1_patchseq_phys_temp_ephys_features.csv` because of the notebook's example code. Getting it directly from the repository or from an external link can save us from a lot of grief.

**Comment by dkobak** [comment]
Hi. Thanks for raising this issue. What you say makes a lot of sense. The only problem is that the file takes up 1Gb of space which is why I haven't pushed it to Github. But I guess it would make sense to make it available elsewhere, e.g. on Zenodo.

Now that I think about it, if I upload `three_traces.pickle`, then I can as well upload other pickle files that store preprocessed data, e.g. the data from the Allen institute (`data/reduced-allen-data/`) and maybe something else. Let me know if you have thoughts about that.

This might have to wait until early July though.

**Comment by RyokoNod** [comment]
Thank you for considering this. 

And yes, other pickle files would be helpful too. The notebooks that took a considerable amount of time are `preprocess-ephys-files.ipynb` and `allen-data-preprocess.ipynb` so I think others will be extremely grateful if they could get pickle files for them. 

I'm not as sure about notebooks`preprocess-morph-SWC-files.ipynb` and `extract-morphometric-features.ipynb` though. I skipped them as the main CSV files were already provided. If the CSV files that belong in `data/processed/morph/features` are important for analysis, it might be nice to have them too.

It's all right if you take until early July. I think I can manage to create the pickle files myself, and if I don't, I can just wait.

**Comment by dkobak** [comment]
Sorry for the delay, but here it goes: https://zenodo.org/record/5118962. I am updating the README of this repository to say which files are available at Zenodo.

**Comment by RyokoNod** [comment]
Thank you so much @dkobak! This is some great help for me.
